# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webhookx < Formula
  desc "an open-source webhooks gateway for message receiving, processing, and delivering."
  homepage "https://github.com/webhookx-io/webhookx"
  version "0.4.0-rc2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webhookx-io/webhookx/releases/download/v0.4.0-rc2/webhookx_0.4.0-rc2_darwin_amd64.tar.gz"
      sha256 "5446e48a3a99eeb6160211f7e0e28df53d51a4353125437e69005d7290c448be"

      def install
        bin.install "webhookx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webhookx-io/webhookx/releases/download/v0.4.0-rc2/webhookx_0.4.0-rc2_darwin_arm64.tar.gz"
      sha256 "01ebdc0aa35531c8beaa7f958c7919c2dcd93b2bced0bba115f4e593bc3e35ab"

      def install
        bin.install "webhookx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/webhookx-io/webhookx/releases/download/v0.4.0-rc2/webhookx_0.4.0-rc2_linux_amd64.tar.gz"
        sha256 "93748f3a2adedad5e1aa585eca8f7cee684ac0f1055d6d2ac278f074cde64c2f"

        def install
          bin.install "webhookx"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/webhookx-io/webhookx/releases/download/v0.4.0-rc2/webhookx_0.4.0-rc2_linux_arm64.tar.gz"
        sha256 "babcbe182c1bef64332cb1ee61a3b62d328f594a275e929c3f6db188edede11a"

        def install
          bin.install "webhookx"
        end
      end
    end
  end

  test do
    system "#{bin}/webhookx", "version"
  end
end
