# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webhookx < Formula
  desc "an open-source webhooks gateway for message receiving, processing, and delivering."
  homepage "https://github.com/webhookx-io/webhookx"
  version "0.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webhookx-io/webhookx/releases/download/v0.8.0/webhookx_0.8.0_darwin_amd64.tar.gz"
      sha256 "d32f396492b607ea85634557efb6ded3623730fbc91826ffb8e38badb8bdd5f1"

      def install
        bin.install "webhookx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webhookx-io/webhookx/releases/download/v0.8.0/webhookx_0.8.0_darwin_arm64.tar.gz"
      sha256 "2c66a21669b28973140450ae50a7eb243476ed28023c8ae31335c4cb9a5bfa21"

      def install
        bin.install "webhookx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/webhookx-io/webhookx/releases/download/v0.8.0/webhookx_0.8.0_linux_amd64.tar.gz"
      sha256 "0b01ddbce4266b06674b5cbbe64be06fc50391476a18efe6736370ba6d1b6e2b"
      def install
        bin.install "webhookx"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/webhookx-io/webhookx/releases/download/v0.8.0/webhookx_0.8.0_linux_arm64.tar.gz"
      sha256 "7350309872fee9a27756b1c99ed527edeeb2ccbd1dc2b0b376010379d08a0090"
      def install
        bin.install "webhookx"
      end
    end
  end

  test do
    system "#{bin}/webhookx", "version"
  end
end
