# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webhookx < Formula
  desc "an open-source webhooks gateway for message receiving, processing, and delivering."
  homepage "https://github.com/webhookx-io/webhookx"
  version "0.6.0-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webhookx-io/webhookx/releases/download/v0.6.0-rc1/webhookx_0.6.0-rc1_darwin_amd64.tar.gz"
      sha256 "c546eb5e632ada73e11d7620c8dc29d73d917cc44bad2f63e4a5e7cc8980e076"

      def install
        bin.install "webhookx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webhookx-io/webhookx/releases/download/v0.6.0-rc1/webhookx_0.6.0-rc1_darwin_arm64.tar.gz"
      sha256 "952f77ca50e19c6587336b8bde36578ff0d3af7bdc510c2cbd1a28f80fb4f022"

      def install
        bin.install "webhookx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/webhookx-io/webhookx/releases/download/v0.6.0-rc1/webhookx_0.6.0-rc1_linux_amd64.tar.gz"
        sha256 "ea7c276d5593ac255d2fa0421a9a51449bdf910f05dc18cc2f8f26d25bd42244"

        def install
          bin.install "webhookx"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/webhookx-io/webhookx/releases/download/v0.6.0-rc1/webhookx_0.6.0-rc1_linux_arm64.tar.gz"
        sha256 "f6ebe55cebc44aac34a256b1a400fa10d342514507d40fa8006144830c6a9e58"

        def install
          bin.install "webhookx"
        end
      end
    end
  end

  test do
    system "#{bin}/webhookx", "version"
  end
end
